<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cruelandunusual</groupId>
        <artifactId>cruelandunusualfull</artifactId>
        <version>0.2.0</version>
    </parent>
    <artifactId>cruelandunusual</artifactId>
    <profiles>
      <profile>
	<id>amd64-x64</id>
	<activation>
	  <os>
	    <family>unix</family>
	    <name>linux</name>
	    <arch>amd64</arch>
	  </os>
	</activation>
	<properties>
	  <lwjgl.natives>natives-linux</lwjgl.natives>
	</properties>
      </profile>
      <profile>
	<id>LINUX</id>
	<activation>
	  <os>
	    <family>unix</family>
	    <name>linux</name>
	    <arch>!amd64</arch>
	  </os>
	</activation>
	<properties>
	  <lwjgl.natives>natives-linux-${os.arch}</lwjgl.natives>
	</properties>
      </profile>
      <profile>
	<id>WINDOWS</id>
	<activation>
	  <os>
	    <family>Windows</family>
	  </os>
	</activation>
	<properties>
	  <lwjgl.natives>natives-windows</lwjgl.natives>
	</properties>
      </profile>
      <profile>
	<id>MACOS</id>
	<activation>
	  <os>
	    <family>mac</family>
	  </os>
	</activation>
	<properties>
	  <lwjgl.natives>natives-macos</lwjgl.natives>
	</properties>
      </profile>
    </profiles>
    <properties>
      <lwjgl.version>3.4.0</lwjgl.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.lwjgl</groupId>
                <artifactId>lwjgl-bom</artifactId>
                <version>${lwjgl.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opencl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opengl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <!--suppress UnresolvedMavenProperty -->
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <!--suppress UnresolvedMavenProperty -->
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20250517</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <archive>
                    <manifest>
                        <addClasspath>true</addClasspath>
                        <mainClass>com.cruelandunusual.CruelAndUnusual</mainClass>
                    </manifest>
                </archive>
                <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                </descriptorRefs>
            </configuration>
        </plugin>
        </plugins>
    </build>
</project>
