package com.cruelandunusual;

public enum Screen {
    TITLE_INIT,
    TITLE,
    GAME_INIT,
    GAME,
    RULES_INIT,
    RULES,
    OPTIONS_INIT,
    OPTIONS,
    WORLD_SELECT_INIT,
    WORLD_SELECT,
    WORLD_OPTIONS_INIT,
    WORLD_OPTIONS,
    CHARACTER_SELECT_INIT,
    CHARACTER_SELECT,
    CHARACTER_OPTIONS_INIT,
    CHARACTER_OPTIONS,
    MULTI_PLAYER_INIT,
    MULTI_PLAYER
}
